on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions

    - run: npm install

    # - run: xvfb-run -a npm test
    - run: xvfb-run -a npm run test:coverage

    # - run: npm run test:coverage
    # - run: npm test

    - name: Package
      run: |
        vsce ls --tree
        vsce package --allow-star-activation

    - uses: actions/upload-artifact@v4
      with:
        name: easy-toggle-settings-artifacts
        path: easy-toggle-settings-*.vsix
        if-no-files-found: error

    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
