on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: ./.github/actions/setup-and-test

    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Validating tag name: ${{ github.ref_name }}"
        if ! [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Invalid tag name format: ${{ github.ref_name }}. Expected format: X.Y.Z"
          exit 1
        fi
        npx vsce publish ${{ github.ref_name }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
